version: '3.7'
services:   
  db-cassandra:
    image: cassandra:4.1.3
    hostname: cassandra
    ports:
      - "0.0.0.0:9042:9042"     
    healthcheck:
      test: ["CMD", "cqlsh","-e describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10      
  
  setup-cassandra:
    image: cassandra:4.1.3
    hostname: cassandra
    command: cqlsh db-cassandra --connect-timeout=30 --request-timeout=6000 -f /setup/setup.cql
    volumes:
      - ./cassandra/scripts:/setup
      - ./cassandra/data:/load-data
    links:
      - "db-cassandra:db-cassandra"       
    depends_on:
        db-cassandra:
            condition: service_healthy      
  
  process-load:
    image: spark-cassandra-test
    environment:            
      - CLASSNAME=Main
    links:
      - "db-cassandra:db-cassandra"             
    #volumes:
    #  - ./cassandra/out:/out
    depends_on:
      setup-cassandra:
          condition: service_completed_successfully        