version: '3.7'
services:   
  redis-host:
    image: redis:7
    ports:
      - "6379:6379"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 15s
      timeout: 10s
      retries: 10      


  process-load:
    image: spark-redis-test
    environment:            
      - CLASSNAME=Main
    volumes:
      - ./persistence/data:/in
    links:
      - "redis-host:redis-host"       
    depends_on:
        redis-host:
            condition: service_healthy        


volumes:
  minio_data: