version: "3.7"
services:
  spark-master:
    image: jupyter/all-spark-notebook
    hostname: spark-master
    # master doesn't need to resolve other nodes.
    env:
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8088
    entrypoint: /usr/local/spark/bin/spark-class
    command: org.apache.spark.deploy.master.Master -h spark-master
    ports:
      - "7077:7077"
      - "8088:8088"
