version: "3.7"
services:
  spark-worker:
    image: jupyter/all-spark-notebook
    # hostname: spark-worker-1
    # Worker have dynamic hostname - this will be set via scripts
    # Work also have extra hosts defined by script
    # need reference to Master and Driver App
    user: root
    environment:
      - SPARK_WORKER_PORT=51815
      - SPARK_WORKER_WEBUI_PORT=4040
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=10g
      - SPARK_WORKER_OPTS="-Dspark.blockManager.port=51814"
    entrypoint: /usr/local/spark/bin/spark-class
    command: org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    ports:
      - "51814:51814"
      - "51815:51815"
      - "4040:4040"      
